### ISSUE TITLE
My advice

### ISSUE THREAD

**Issue by drogs** [grandiloquent/VideoBrowser#2]
I recommend removing the images that contain pornography, because it's against Github's rules. I'm just letting you know, i'm not going to do anything about it. Just trying to help you.

Google translate: 
我建议删除包含色情内容的图片，因为这违反了 Github 的规则。我只是让你知道，我不会对此做任何事情。只是想帮助你。

**Comment by grandiloquent** [comment]
@drogs Thanks you.
