### ISSUE TITLE
下载youtube视频速度只有100kb/s左右

### ISSUE THREAD

**Issue by BrunuhVille** [grandiloquent/VideoBrowser#5]
安卓安装软件，左上角复制网址下载
速度大概只有100kb/s左右，本身梯子速度是ok的大概20mbps的速度

**Comment by grandiloquent** [comment]
@BrunuhVille YouTube的解析是引用的 https://github.com/HaarigerHarald/android-youtubeExtractor 这个库，可以 
https://github.com/HaarigerHarald/android-youtubeExtractor/issues ，稍后也去测试一下，如果能够找到问题再回复你 :grinning: 。
